Makefile and configure modifications

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -301,6 +301,15 @@ create_make_rules()
 	echo "$_ar"
 	echo "AR=$_ar" >> Make.Rules
 
+	echo -n "checking for ld... "
+	_ld=$(which ld)
+	if [ $? -ne 0 ] ; then
+		echo "can't find ld(1)!"
+		exit 1
+	fi
+	echo "$_ld"
+	echo "LD=$_ld" >> Make.Rules
+
 	echo -n "checking for ranlib... "
 	_ranlib=$(which ranlib)
 	if [ $? -ne 0 ] ; then # don't found ranlib
@@ -562,7 +571,7 @@ EOF
 print_config()
 {
 	echo 
-	echo -e "\e[31;1mEnvironment seems fine! ;)\e[0m\n\nConfigure picked following defaults, options and paths:"
+	echo -e "Environment seems fine! ;)\n\nConfigure picked following defaults, options and paths:"
 	echo -e "Please validate this values"
 	echo
 	make show
